"""
By: Jagrit Aggarwal
Student
Thapar Institute of Engineering & Technology,
Patiala-147001, Punjab, India.

Demo of 'Multiple Linear Regression by user defined functions and confirmed by inbuilt function'
"""

In [1]:
import pandas as pd
import plotly.express as px
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score

In [2]:
df=pd.read_csv('C://Users//HP//Downloads//Admission_Predict.csv',index_col="Serial No.")

In [3]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
Serial No.                                                               
1                 337          118                  4  4.5   4.5  9.65   
2                 324          107                  4  4.0   4.5  8.87   
3                 316          104                  3  3.0   3.5  8.00   
4                 322          110                  3  3.5   2.5  8.67   
5                 314          103                  2  2.0   3.0  8.21   
...               ...          ...                ...  ...   ...   ...   
396               324          110                  3  3.5   3.5  9.04   
397               325          107                  3  3.0   3.5  9.11   
398               330          116                  4  5.0   4.5  9.45   
399               312          103                  3  3.5   4.0  8.78   
400               333          117                  4  5.0   4.0  9.66   

            Research  Chance of Admit   
Serial No.                              
1                  1              0.92  
2                  1              0.76  
3                  1              0.72  
4                  1              0.80  
5                  0              0.65  
...              ...               ...  
396                1              0.82  
397                1              0.84  
398                1              0.91  
399                0              0.67  
400                1              0.95  

[400 rows x 8 columns]

In [4]:
df.isna().sum()

GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [5]:
df.corr()

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.835977           0.668976  0.612831   
TOEFL Score         0.835977     1.000000           0.695590  0.657981   
University Rating   0.668976     0.695590           1.000000  0.734523   
SOP                 0.612831     0.657981           0.734523  1.000000   
LOR                 0.557555     0.567721           0.660123  0.729593   
CGPA                0.833060     0.828417           0.746479  0.718144   
Research            0.580391     0.489858           0.447783  0.444029   
Chance of Admit     0.802610     0.791594           0.711250  0.675732   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.557555  0.833060  0.580391          0.802610  
TOEFL Score        0.567721  0.828417  0.489858          0.791594  
University Rating  0.660123  0.746479  0.447783          0.711250  
SOP                0.729593  0.718144  0.444029          0.675732  
LOR                1.000000  0.670211  0.396859          0.669889  
CGPA               0.670211  1.000000  0.521654          0.873289  
Research           0.396859  0.521654  1.000000          0.553202  
Chance of Admit    0.669889  0.873289  0.553202          1.000000

### Seprating independent and dependent variable

In [6]:
x=df.iloc[:,[0,1,2,3,4,5,6]]

In [7]:
y=df.iloc[:,[7]]

In [8]:
x

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
Serial No.                                                               
1                 337          118                  4  4.5   4.5  9.65   
2                 324          107                  4  4.0   4.5  8.87   
3                 316          104                  3  3.0   3.5  8.00   
4                 322          110                  3  3.5   2.5  8.67   
5                 314          103                  2  2.0   3.0  8.21   
...               ...          ...                ...  ...   ...   ...   
396               324          110                  3  3.5   3.5  9.04   
397               325          107                  3  3.0   3.5  9.11   
398               330          116                  4  5.0   4.5  9.45   
399               312          103                  3  3.5   4.0  8.78   
400               333          117                  4  5.0   4.0  9.66   

            Research  
Serial No.            
1                  1  
2                  1  
3                  1  
4                  1  
5                  0  
...              ...  
396                1  
397                1  
398                1  
399                0  
400                1  

[400 rows x 7 columns]

In [9]:
y

Chance of Admit 
Serial No.                  
1                       0.92
2                       0.76
3                       0.72
4                       0.80
5                       0.65
...                      ...
396                     0.82
397                     0.84
398                     0.91
399                     0.67
400                     0.95

[400 rows x 1 columns]

### Spliting into train and test

In [10]:
n_train=int((0.8)*(df.shape[0]))

In [11]:
n_test=df.shape[0]-n_train

In [12]:
x_train=x.iloc[0:n_train,:]

In [13]:
x_train

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
Serial No.                                                               
1                 337          118                  4  4.5   4.5  9.65   
2                 324          107                  4  4.0   4.5  8.87   
3                 316          104                  3  3.0   3.5  8.00   
4                 322          110                  3  3.5   2.5  8.67   
5                 314          103                  2  2.0   3.0  8.21   
...               ...          ...                ...  ...   ...   ...   
316               308          104                  2  2.5   3.0  8.07   
317               298          101                  2  1.5   2.0  7.86   
318               300           99                  1  1.0   2.5  8.01   
319               324          111                  3  2.5   2.0  8.80   
320               327          113                  4  3.5   3.0  8.69   

            Research  
Serial No.            
1                  1  
2                  1  
3                  1  
4                  1  
5                  0  
...              ...  
316                0  
317                0  
318                0  
319                1  
320                1  

[320 rows x 7 columns]

In [14]:
x_test=x.iloc[0:n_test,:]

In [15]:
x_test

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
Serial No.                                                               
1                 337          118                  4  4.5   4.5  9.65   
2                 324          107                  4  4.0   4.5  8.87   
3                 316          104                  3  3.0   3.5  8.00   
4                 322          110                  3  3.5   2.5  8.67   
5                 314          103                  2  2.0   3.0  8.21   
...               ...          ...                ...  ...   ...   ...   
76                329          114                  2  2.0   4.0  8.56   
77                327          112                  3  3.0   3.0  8.72   
78                301           99                  2  3.0   2.0  8.22   
79                296           95                  2  3.0   2.0  7.54   
80                294           93                  1  1.5   2.0  7.36   

            Research  
Serial No.            
1                  1  
2                  1  
3                  1  
4                  1  
5                  0  
...              ...  
76                 1  
77                 1  
78                 0  
79                 1  
80                 0  

[80 rows x 7 columns]

In [16]:
y_train=y.iloc[0:n_train,:]

In [17]:
y_train

Chance of Admit 
Serial No.                  
1                       0.92
2                       0.76
3                       0.72
4                       0.80
5                       0.65
...                      ...
316                     0.65
317                     0.54
318                     0.58
319                     0.79
320                     0.80

[320 rows x 1 columns]

In [18]:
y_test=y.iloc[0:n_test,:]

In [19]:
y_test

Chance of Admit 
Serial No.                  
1                       0.92
2                       0.76
3                       0.72
4                       0.80
5                       0.65
...                      ...
76                      0.72
77                      0.74
78                      0.64
79                      0.44
80                      0.46

[80 rows x 1 columns]

### Appying MLR on training set

In [20]:
X=x_train.copy()

In [21]:
Y=y_train.copy()

In [22]:
a=[1]*n_train

In [23]:
X.insert(0, "all 1", a)

In [24]:
X

all 1  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
Serial No.                                                                      
1               1        337          118                  4  4.5   4.5  9.65   
2               1        324          107                  4  4.0   4.5  8.87   
3               1        316          104                  3  3.0   3.5  8.00   
4               1        322          110                  3  3.5   2.5  8.67   
5               1        314          103                  2  2.0   3.0  8.21   
...           ...        ...          ...                ...  ...   ...   ...   
316             1        308          104                  2  2.5   3.0  8.07   
317             1        298          101                  2  1.5   2.0  7.86   
318             1        300           99                  1  1.0   2.5  8.01   
319             1        324          111                  3  2.5   2.0  8.80   
320             1        327          113                  4  3.5   3.0  8.69   

            Research  
Serial No.            
1                  1  
2                  1  
3                  1  
4                  1  
5                  0  
...              ...  
316                0  
317                0  
318                0  
319                1  
320                1  

[320 rows x 8 columns]

In [25]:
X=X.to_numpy()

In [26]:
X

array([[  1.  , 337.  , 118.  , ...,   4.5 ,   9.65,   1.  ],
       [  1.  , 324.  , 107.  , ...,   4.5 ,   8.87,   1.  ],
       [  1.  , 316.  , 104.  , ...,   3.5 ,   8.  ,   1.  ],
       ...,
       [  1.  , 300.  ,  99.  , ...,   2.5 ,   8.01,   0.  ],
       [  1.  , 324.  , 111.  , ...,   2.  ,   8.8 ,   1.  ],
       [  1.  , 327.  , 113.  , ...,   3.  ,   8.69,   1.  ]])

In [27]:
Y=Y.to_numpy()

### B=(X'X)inv*(X'Y)

In [28]:
X_t=np.transpose(X)

In [29]:
X_t_X=np.matmul(X_t,X)

In [30]:
X_t_X_inv=np.linalg.inv(X_t_X)

In [31]:
X_t_Y=np.matmul(X_t,Y)

In [32]:
B=np.matmul(X_t_X_inv,X_t_Y)

In [33]:
B

array([[-1.24998779],
       [ 0.00169643],
       [ 0.00297888],
       [ 0.0086779 ],
       [-0.00546856],
       [ 0.02770287],
       [ 0.11618532],
       [ 0.01869737]])

## Model Performance

In [34]:
y_test_=y_test.to_numpy()

In [35]:
x_test

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
Serial No.                                                               
1                 337          118                  4  4.5   4.5  9.65   
2                 324          107                  4  4.0   4.5  8.87   
3                 316          104                  3  3.0   3.5  8.00   
4                 322          110                  3  3.5   2.5  8.67   
5                 314          103                  2  2.0   3.0  8.21   
...               ...          ...                ...  ...   ...   ...   
76                329          114                  2  2.0   4.0  8.56   
77                327          112                  3  3.0   3.0  8.72   
78                301           99                  2  3.0   2.0  8.22   
79                296           95                  2  3.0   2.0  7.54   
80                294           93                  1  1.5   2.0  7.36   

            Research  
Serial No.            
1                  1  
2                  1  
3                  1  
4                  1  
5                  0  
...              ...  
76                 1  
77                 1  
78                 0  
79                 1  
80                 0  

[80 rows x 7 columns]

In [36]:
x1=list()
x2=list()
x3=list()
x4=list()
x5=list()
x6=list()
x7=list()
for i in x_test["GRE Score"]:
    x1.append(i)
for i in x_test["TOEFL Score"]:
    x2.append(i)
for i in x_test["University Rating"]:
    x3.append(i)
for i in x_test["SOP"]:
    x4.append(i)
for i in x_test["LOR "]:
    x5.append(i)
for i in x_test["CGPA"]:
    x6.append(i)
for i in x_test["Research"]:
    x7.append(i)
    

In [37]:
B[1]

array([0.00169643])

In [38]:
y_pred=[(B[0] + B[1]*(X1) + B[2]*(X2) + B[3]*(X3) + B[4]*(X4) + B[5]*(X5) + B[6]*(X6) + B[7]*(X7) )for X1,X2,X3,X4,X5,X6,X7 in zip(x1,x2,x3,x4,x5,x6,x7)]

In [39]:
residuals=[(o-p)**2 for o,p in zip(y_test_,y_pred)]

In [40]:
def summation(val):
    res=0
    for i in val:
        res+=i
    return res

In [41]:
summation(residuals)

array([0.60986945])

In [42]:
mse=summation(residuals)/x_test.shape[0]

In [43]:
mse

array([0.00762337])

In [44]:
rmse=(mse)**0.5

In [45]:
rmse

array([0.0873119])


# Inbuilt Functions

In [46]:
from sklearn.linear_model import LinearRegression

In [47]:
regressor=LinearRegression()

In [48]:
regressor.fit(x_train,y_train)

LinearRegression()

In [49]:
regressor.coef_

array([[ 0.00169643,  0.00297888,  0.0086779 , -0.00546856,  0.02770287,
         0.11618532,  0.01869737]])

In [50]:
regressor.intercept_

array([-1.24998779])

In [51]:
y_pred_in=regressor.predict(x_test)

In [52]:
 from sklearn.metrics import mean_squared_error

In [53]:
mean_squared_error(y_pred_in, y_test, squared=True)

0.007623368079780038

In [54]:
rms = mean_squared_error(y_pred_in, y_test, squared=False)
rms

0.08731190113483979